ichrisbirch/app/forms/books.py
from flask_wtf import FlaskForm
from wtforms import BooleanField
from wtforms import DateField
from wtforms import FloatField
from wtforms import IntegerField
from wtforms import StringField
from wtforms import TextAreaField
from wtforms.validators import URL
from wtforms.validators import DataRequired
from wtforms.validators import Optional


class BookCreateForm(FlaskForm):
    isbn = StringField('ISBN', validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    tags = StringField('Tags', validators=[DataRequired()])
    goodreads_url = StringField('Goodreads URL', validators=[Optional(), URL()])
    priority = IntegerField('Priority', validators=[Optional()])
    purchase_date = DateField('Purchase Date', validators=[Optional()], render_kw={'type': 'date'})
    purchase_price = FloatField('Purchase Price', validators=[Optional()])
    sell_date = DateField('Sell Date', validators=[Optional()], render_kw={'type': 'date'})
    sell_price = FloatField('Sell Price', validators=[Optional()])
    read_start_date = DateField('Read Start Date', validators=[Optional()], render_kw={'type': 'date'})
    read_finish_date = DateField('Read Finish Date', validators=[Optional()], render_kw={'type': 'date'})
    rating = IntegerField('Rating', validators=[Optional()])
    abandoned = BooleanField('Abandoned', validators=[Optional()])
    location = StringField('Location', validators=[Optional()])
    notes = TextAreaField('Notes', render_kw={'rows': 3}, validators=[Optional()])


class BookUpdateForm(FlaskForm):
    isbn = StringField('ISBN', validators=[Optional()])
    title = StringField('Title', validators=[Optional()])
    author = StringField('Author', validators=[DataRequired()])
    tags = StringField('Tags', validators=[Optional()])
    goodreads_url = StringField('Goodreads URL', validators=[Optional(), URL()])
    priority = IntegerField('Priority', validators=[Optional()])
    purchase_date = DateField('Purchase Date', validators=[Optional()], render_kw={'type': 'date'})
    purchase_price = FloatField('Purchase Price', validators=[Optional()])
    sell_date = DateField('Sell Date', validators=[Optional()], render_kw={'type': 'date'})
    sell_price = FloatField('Sell Price', validators=[Optional()])
    read_start_date = DateField('Read Start Date', validators=[Optional()], render_kw={'type': 'date'})
    read_finish_date = DateField('Read Finish Date', validators=[Optional()], render_kw={'type': 'date'})
    rating = IntegerField('Rating', validators=[Optional()])
    abandoned = BooleanField('Abandoned', validators=[Optional()])
    location = StringField('Location', validators=[Optional()])
    notes = TextAreaField('Notes', render_kw={'rows': 3}, validators=[Optional()])

ichrisbirch/app/routes/books.py
import structlog
from fastapi import status
from flask import Blueprint
from flask import Response
from flask import current_app
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import login_required

from ichrisbirch import schemas
from ichrisbirch.api.client.exceptions import APIHTTPError
from ichrisbirch.api.client.logging_client import logging_flask_session_client
from ichrisbirch.app import forms

logger = structlog.get_logger()

blueprint = Blueprint('books', __name__, template_folder='templates/books', static_folder='static')


@blueprint.before_request
@login_required
def enforce_login():
    pass


@blueprint.route('/', methods=['GET', 'POST'])
def index():
    base_url = current_app.config['SETTINGS'].api_url
    with logging_flask_session_client(base_url=base_url) as client:
        books_api = client.resource('books', schemas.Book)
        if search := request.args.get('search'):
            books = books_api.get_many('search', params={'q': search})
        else:
            books = books_api.get_many()
        return render_template('books/index.html', books=books)


@blueprint.route('/add/', methods=['GET', 'POST'])
def add():
    settings = current_app.config['SETTINGS']
    create_form = forms.BookCreateForm()
    goodreads_info_endpoint = f'{settings.api_url}/books/goodreads/'
    return render_template('books/add.html', create_form=create_form, goodreads_info_endpoint=goodreads_info_endpoint)


@blueprint.route('/crud/', methods=['POST'])
def crud():
    base_url = current_app.config['SETTINGS'].api_url
    with logging_flask_session_client(base_url=base_url) as client:
        books_api = client.resource('books', schemas.Book)
        data = request.form.to_dict()
        action = data.pop('action')

        match action:
            case 'add':
                form = forms.BookCreateForm(request.form)
                if form.validate_on_submit():
                    try:
                        existing = books_api.get_one(f'isbn/{data["isbn"]}')
                    except APIHTTPError as e:
                        if e.status_code == 404:
                            existing = None
                        else:
                            raise
                    if existing:
                        flash(f'already exists: {data["isbn"]}', 'warning')
                        logger.warning('book_already_exists', isbn=data['isbn'])
                    else:
                        # convert string field of tags to list for storing in postgres array
                        data['tags'] = [tag.strip().lower() for tag in data['tags'].split(',')]
                        books_api.post(json=data)
                        flash(f'Added: {data["title"]}', 'success')
                else:
                    flash('Form validation failed', 'error')
                    logger.warning('book_form_validation_failed', errors=form.errors)
                    for field, errors in form.errors.items():
                        for error in errors:
                            flash(f'{field}: {error}', 'error')
            case 'delete':
                books_api.delete(data.get('id'))

            case _:
                return Response(f'Method/Action {action} not allowed', status=status.HTTP_405_METHOD_NOT_ALLOWED)

        return redirect(request.referrer or url_for('books.index'))

ichrisbirch/app/templates/books/add.html
{% extends"books/base.html" %}

{% block title %}Add New Book{% endblock title %}

{% block content %}
<div class="grid grid--one-column">
  <div class="add-item-wrapper">
    <h2>Add New Book</h2>
    <form class="add-item-form" method="post" action="{{ url_for('books.crud') }}">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

      <div class="add-item-form__item">
        {{ create_form.isbn.label }}
        {{ create_form.isbn(class_="textbox") }}
      </div>

      <div class="add-item-form__item">
        <button id="populateButton" type="button" class="button" formnovalidate>
          <span class="button__text">Auto Populate from ISBN</span>
        </button>
      </div>

      <div class="add-item-form__item">
        {{ create_form.title.label }}
        {{ create_form.title(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.author.label }}
        {{ create_form.author(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.tags.label }}
        {{ create_form.tags(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.goodreads_url.label }}
        {{ create_form.goodreads_url(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.priority.label }}
        {{ create_form.priority(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.purchase_date.label }}
        {{ create_form.purchase_date(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.purchase_price.label }}
        {{ create_form.purchase_price(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.sell_date.label }}
        {{ create_form.sell_date(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.sell_price.label }}
        {{ create_form.sell_price(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.read_start_date.label }}
        {{ create_form.read_start_date(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.read_finish_date.label }}
        {{ create_form.read_finish_date(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.rating.label }}
        {{ create_form.rating(class_="textbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.abandoned.label }}
        {{ create_form.abandoned(class_="checkbox") }}
      </div>
      <div class="add-item-form__item">
        {{ create_form.location.label }}
        {{ create_form.location(class_="textbox") }}
      </div>
      <div class="add-item-form__item add-item-form__item--full-width">
        {{ create_form.notes.label }}
        {{ create_form.notes(class_="textbox") }}
      </div>
      <div class="add-item-form__item add-item-form__item--full-width">
        <button type="submit" name="action" class="button" value="add">
          <span class="button__text">Add New Book</span>
        </button>
      </div>
    </form>
  </div>
</div>

<div id="goodreadsInfoEndpoint" class="hidden-data">{{ goodreads_info_endpoint }}</div>
<script>
  document.querySelector('#populateButton').addEventListener('click', function (event) {
    event.preventDefault();

    const isbnField = document.querySelector('.add-item-form input[name="isbn"]');
    const titleField = document.querySelector('.add-item-form input[name="title"]');
    const authorField = document.querySelector('.add-item-form input[name="author"]');
    const tagsField = document.querySelector('.add-item-form input[name="tags"]');
    const goodreadsUrlField = document.querySelector('.add-item-form input[name="goodreads_url"]');
    const goodreadsInfoEndpoint = document.getElementById('goodreadsInfoEndpoint').textContent;

    fetch(goodreadsInfoEndpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        isbn: isbnField.value
      })
    })
      .then(response => response.json())
      .then(data => {
        titleField.value = data.title;
        authorField.value = data.author;
        tagsField.value = data.tags;
        goodreadsUrlField.value = data.goodreads_url;
      })
      .catch(error => console.error('Error:', error));
  });
</script>
{% endblock content %}

ichrisbirch/app/templates/books/base.html
{% extends"base.html" %}

{% block meta %}
{% endblock meta %}

{% block scripts %}{% endblock scripts %}

{% block app_navigation %}
<ul data-secondary>
  <li><a href="{{ url_for('books.index') }}">Books</a></li>
  <li><a href="{{ url_for('books.add') }}">Add Book</a></li>
  <li>
    <form class="task-search-form" method="get" action="{{ url_for('books.index') }}">
      <input type="text" class="textbox" name="search" id="search">
      <button type="submit" class="button">
        <span class="button__text">Search</span>
      </button>
    </form>
  </li>
</ul>
{% endblock app_navigation %}

{% block content %}{% endblock content %}

ichrisbirch/app/templates/books/index.html
{% extends"books/base.html" %}

{% block title %}Books{% endblock title %}

{% block content %}
<div class="grid grid--one-column-full">
  <div class="grid__item">
    <ul class="books books__header">
      <li class="books__column">ISBN</li>
      <li class="books__column">Title</li>
      <li class="books__column">Author</li>
      <li class="books__column">Tags</li>
      <li class="books__column">Goodreads URL</li>
      <li class="books__column">Priority</li>
      <li class="books__column">Purchase Date</li>
      <li class="books__column">Purchase Price</li>
      <li class="books__column">Sell Date</li>
      <li class="books__column">Sell Price</li>
      <li class="books__column">Read Start Date</li>
      <li class="books__column">Read Finish Date</li>
      <li class="books__column">Rating</li>
      <li class="books__column">Abandoned</li>
      <li class="books__column">Location</li>
      <li class="books__column">Notes</li>
      <li class="books__column">Delete</li>
    </ul>
    {% for book in books %}
    <ul class="books books__item">
      <li class="books__column">{{ book.isbn }}</li>
      <li class="books__column">{{ book.title }}</li>
      <li class="books__column">{{ book.author }}</li>
      <li class="books__column">{{ book.tags | join(', ') }}</li>
      <li class="books__column">
        {% if book.goodreads_url %}
        <a href="{{ book.goodreads_url }}" target="_blank">{{ book.isbn }}</a>
        {% else %}
        N/A
        {% endif %}
      </li>
      <li class="books__column">{{ book.priority if book.priority else '' }}</li>
      <li class="books__column">{{ book.purchase_date if book.purchase_date else '' }}</li>
      <li class="books__column">{{ book.purchase_price if book.purchase_price else '' }}</li>
      <li class="books__column">{{ book.sell_date if book.sell_date else '' }}</li>
      <li class="books__column">{{ book.sell_price if book.sell_price else '' }}</li>
      <li class="books__column">{{ book.read_start_date if book.read_start_date else '' }}</li>
      <li class="books__column">{{ book.read_finish_date if book.read_finish_date else '' }}</li>
      <li class="books__column">{{ book.rating if book.rating else '' }}</li>
      <li class="books__column">{{ 'Yes' if book.abandoned else 'No' }}</li>
      <li class="books__column">{{ book.location if book.location else '' }}</li>
      <li class="books__column">{{ book.notes if book.notes else '' }}</li>
      <li class="books__column">
        <form method="post" action="{{ url_for('books.crud') }}">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <input type="hidden" name="id" value="{{ book.id }}">
          <button type="submit" name="action" class="button--hidden" value="delete">
            <i class="button-icon danger fa-regular fa-trash-can"></i>
          </button>
        </form>
      </li>
    </ul>
    {% endfor %}
  </div>
</div>
{% endblock content %}